### ISSUE TITLE
latest.webp

### ISSUE THREAD

**Issue by robertsky** [hackerspacesg/s3cam#1]
Can we still have latest file in webp as well? Let me work out the fallback for https://github.com/hackerspacesg/hackerspace.sg/issues/129.

With over 63% of last 30 day's sessions' browsers supporting webp, the costs saving should be significant.

![screen shot 2015-10-24 at 11 15 33 pm](https://cloud.githubusercontent.com/assets/1820367/10711154/679f043e-7aa5-11e5-8540-91fc9789984f.png)

http://caniuse.com/#search=webp

**Comment by kaihendry** [comment]
Come on the cost savings would be miniscule.

What about the added costs?
- complexity in explaining we have two latest images. Imagine someone links the WebP and shares to friend on IOS. Result? A crap UX.
- complexity in browser falling back to jpeg in the case they don't support webp
- cost in upload two WebP files instead of just 1

The 1024x768 jpeg will be fine. KISS

**Comment by valentine** [comment]
Two years later and iOS still doesn't support WebP. Heh heh.

**Comment by robertsky** [comment]
just realised that at the time of writing this issue, the fallback was already done... sorry @kaihendry!
